name: chemformer
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - backcall=0.2.0
  - brotli-python=1.0.9
  - ca-certificates=2024.9.24
  - cachecontrol=0.12.11
  - cachy=0.3.0
  - charset-normalizer=3.3.2
  - clikit=0.6.2
  - decorator=5.1.1
  - entrypoints=0.4
  - html5lib=1.1
  - ipykernel=5.5.5
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - jupyter_client=5.3.4
  - jupyter_core=4.5.0
  - libcxx=14.0.6
  - libffi=3.3
  - libsodium=1.0.18
  - lockfile=0.12.2
  - matplotlib-inline=0.1.6
  - msgpack-python=1.0.3
  - ncurses=6.4
  - openssl=1.1.1w
  - parso=0.8.3
  - pastel=0.2.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pygments=2.11.2
  - pylev=1.3.0
  - pysocks=1.7.1
  - python=3.7.11
  - python_abi=3.7
  - pyzmq=24.0.1
  - readline=8.2
  - requests-toolbelt=0.9.1
  - shellingham=1.5.0
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - traitlets=5.1.1
  - webencodings=0.5.1
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - alembic==1.12.1
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - apscheduler==3.10.4
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==23.2.0
      - autopage==0.5.2
      - backports-cached-property==1.0.2
      - backports-zoneinfo==0.2.1
      - black==23.3.0
      - build==0.10.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.15.1
      - cfgv==3.3.1
      - chemformer==2.1.0
      - cleo==2.1.0
      - click==8.1.7
      - cliff==3.10.1
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorlog==6.8.2
      - coverage==7.2.7
      - crashtest==0.4.1
      - deepspeed==0.15.4
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - dulwich==0.21.7
      - eco2ai==0.3.9
      - exceptiongroup==1.2.0
      - fastapi==0.98.0
      - filelock==3.12.2
      - flake8==5.0.4
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - greenlet==3.0.3
      - grpcio==1.62.1
      - hjson==3.1.0
      - hydra==2.5
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - identify==2.5.24
      - idna==3.6
      - importlib-metadata==4.2.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - installer==0.7.0
      - isort==5.11.5
      - jaraco-classes==3.2.3
      - jsonschema==4.17.3
      - keyring==23.13.1
      - lightning-utilities==0.10.1
      - mako==1.2.4
      - markdown==3.3.4
      - markupsafe==2.1.5
      - mccabe==0.7.0
      - more-itertools==9.1.0
      - multidict==6.0.5
      - mypy==1.4.1
      - mypy-extensions==1.0.0
      - ninja==1.11.1.1
      - nodeenv==1.8.0
      - numpy==1.21.6
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - optuna==2.10.1
      - packaging==24.0
      - pandas==1.3.5
      - pathspec==0.11.2
      - pbr==6.0.0
      - pillow==9.5.0
      - pkginfo==1.10.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - pluggy==1.2.0
      - poetry==1.5.1
      - poetry-core==1.6.1
      - poetry-plugin-export==1.4.0
      - pre-commit==2.20.0
      - prettytable==3.7.0
      - protobuf==3.20.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycodestyle==2.9.1
      - pycparser==2.21
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pyflakes==2.5.0
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyproject-hooks==1.2.0
      - pyrsistent==0.19.3
      - pysmilesutils==1.1.0
      - pytest==7.4.4
      - pytest-cov==4.1.0
      - pytest-datadir==1.4.1
      - pytest-mock==3.10.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.2.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - rapidfuzz==3.4.0
      - rdkit==2022.9.3
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scipy==1.7.3
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - setuptools==68.0.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - starlette==0.27.0
      - stevedore==3.5.2
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.5
      - torch==1.8.1
      - torchmetrics==0.11.4
      - tornado==6.2
      - tqdm==4.66.2
      - trove-classifiers==2024.10.21.16
      - typed-ast==1.5.5
      - typing-extensions==4.7.1
      - tzlocal==5.1
      - urllib3==2.0.7
      - virtualenv==20.4.7
      - wandb==0.16.5
      - wcwidth==0.2.13
      - werkzeug==2.2.3
      - wheel==0.42.0
      - xattr==0.10.1
      - yarl==1.9.4
      - zipp==3.15.0

