# @package _global_

defaults:
  # override config either in this file or using experiment config
  - _self_
  - experiment: null # experiment configs allow for version control of specific hyperparameters


# Setting
batch_size: 64
n_beams: 10
n_unique_beams: null
n_gpus: 0

# Data
data_path: "/Users/prishasatwani/Documents/Chemformer/uspto_50_first5.pickle"
output_sampled_smiles: null
vocabulary_path: bart_vocab_downstream.json
task: forward_prediction    # ["forward_prediction", "backward_prediction", "mol_opt"]
i_chunk: 0
n_chunks: 1
data_device: cuda

# Model
model_path: ".../Chemformer/combined.ckpt" 
model_type: bart            # ["bart", "unified"]
dataset_part: full      # ["full", "train", "val", "test"]
train_mode: eval

datamodule: [molbart.data.seq2seq_data.Uspto50DataModule]
  #- SynthesisDataModule
  